### ISSUE TITLE
Redis Connector 5.2 - Mule 4 - Incorrect Mule Runtime Version

### ISSUE THREAD

**Issue by bharathChamala** [mulesoft/docs-connectors#1001]
Team,

Redis Connector Page shows incorrect Mule Runtime Version 

div class="flex align-center justify-justified row">
--
  | <div class="col">Runtime</div>
  | <div class="col">Mule 5.2 or later</div>

Page Link : https://docs.mulesoft.com/redis-connector/5.2/

![image](https://user-images.githubusercontent.com/20515902/91459313-bc6e0080-e843-11ea-871e-d153dc3a401c.png)

**Comment by valkyrie69** [comment]
@bharathChamala Thank you for pointing this out. It has been fixed.
