### ISSUE TITLE
Code samples do not work

### ISSUE THREAD

**Issue by timothybryant** [mulesoft/docs-connectors#1124]
The code samples provided for this page do not reflect their description.

**Comment by valkyrie69** [comment]
Hi @timothybryant Can you please provide more details about which connector documentation you are referring to and provide a link to the specific page so we can take a look? Unfortunately, this mechanism doesn't provide the page you were on when you made the comment. 
Thank you!
Valkyrie

**Comment by timothybryant** [comment]
Thank you for following up Valkyrie.  It is the WebSocket Connector
example:
https://docs.mulesoft.com/websockets-connector/1.0/websockets-connector-examples

The Quote Aggregator and Client Implementation configurations do not
perform the tasks that are described on this page.

It would also be nice to describe the steps required to run in either
Anypoint Studio on CloudHub.  I don't believe that the HTTP Listener and
WebSocket configs are configured to run in either environment w/o
modifications to the URLs.

Sincerely,

<http://www.mulesoft.com/>
*Timm Bryant,* Principal Solution Engineer

20 W. Kinzie Street, Chicago, IL 60654

*M 402.802.5 <555.555.5555>879*

<https://www.linkedin.com/company/mulesoft>   <https://twitter.com/mulesoft>
   <https://www.facebook.com/MuleSoft>   <https://videos.mulesoft.com/> We're
hiring! <http://www.mulesoft.com/careers>


*NOTICE: This e-mail may contain confidential information. Any pricing
information contained in this communication is confidential MuleSoft
information. If you are not the addressee or the intended recipient please
do not read this e-mail and please immediately delete this e-mail message
and any attachments from your network mail system. If you are the addressee
or the intended recipient and you save or print a copy of this e-mail,
please place it in an appropriate file, depending on whether confidential
information is contained in the message, and please treat all MuleSoft
confidential information with heightened protection.*

**Comment by valkyrie69** [comment]
Hi @timothybryant Thank you for the details. We will open a Jira ticket for this and work with dev to update the documentation accordingly.

**Comment by valkyrie69** [comment]
We no longer use Jira to track issues, so I can't confirm this was resolved. I am assuming it was. This issue has exceeded the time limit for a timely merge. @timothybryant If this issue has not been resolved, please open a new issue or PR.
