### ISSUE TITLE
Zuora Connector

### ISSUE THREAD

**Issue by Yext-ABhatt** [mulesoft/docs-connectors#1176]
We are using Mulesoft Zuora Connector 3.2.0.20191114132 with Anypoint 6. While most of the operations works just fine, I am facing issue with Operation 'Get Export File Content' and I am getting 405 Not supported. I am doing following:
1) Create Export using Operation "Create" and type "Export"
2) Find export using operation "Find" and check status of Export. Once Export is ready, 
3) Get content using "Get Export File Content". 
First two operations works just fine. But in 3rd, I get 405 Not supported.

**Comment by valkyrie69** [comment]
@Yext-ABhatt Thank you for reporting this issue. I will follow up with dev.

**Comment by gastonbritomulesoft** [comment]
Hi @Yext-ABhatt , please contact Mulesoft Support to request assistance with the issue that you're facing.
