### ISSUE TITLE
Get session id operation not documented on Salesforce Connector Reference

### ISSUE THREAD

**Issue by jorgegarciamule** [mulesoft/docs-connectors#1370]
"Get session id" is present in version 10.10.2 but not documented in this page:
https://docs.mulesoft.com/salesforce-connector/10.10/salesforce-connector-reference

**Comment by valkyrie69** [comment]
> "Get session id" is present in version 10.10.2 but not documented in this page:
> https://docs.mulesoft.com/salesforce-connector/10.10/salesforce-connector-reference

Thank you, Jorge. I will follow up on this!

**Comment by jorgegarciamule** [comment]
Looks like I was wrong. This operation was not re-added to version 10 of the connector, so it's good as it is.
