### ISSUE TITLE
wrong affirmation on "List Files Using the File Connector" section

### ISSUE THREAD

**Issue by mtcarvalho** [mulesoft/docs-connectors#1489]
The second item of the first section inside [File List](https://docs.mulesoft.com/file-connector/1.3/file-list) page says that 

> The file’s attributes section carries the file’s metadata (such as name, creation time, and size).

Shouldn't it be the below affirmation?

> The **message** attributes section carries the file’s metadata (such as name, creation time, and size).

The message inside the array returned by this operation the one which has attributes.

**Comment by kevintroller** [comment]
Hi @mtcarvalho Thank you for your contribution. We have moved the changes to a new pull request.
https://github.com/mulesoft/docs-connectors/pull/2326
