### ISSUE TITLE
Documentation of Kafka 3.0 conector

### ISSUE THREAD

**Issue by felpasl** [mulesoft/docs-connectors#1764]
I'm able to connect with Azure Event Hub only with kafka 3.0 connector, but the offset are not correct started getting the consumer group info form the server, starting aways in 0 offset.

I need the documentation of 3.0 connector, but the values on configuration etc is from 4.0 connector

**Comment by sathya0** [comment]
Hi @felpasl! Thanks for the feedback. The Kafka 3.0 documentation has been updated [in this PR](https://github.com/mulesoft/docs-connectors/pull/1934/files) and is reflected [on the docs site](https://docs.mulesoft.com/kafka-connector/3.0/kafka-connector-reference).
