### ISSUE TITLE
Outdated information regarding Workday Connector "Test Connection"

### ISSUE THREAD

**Issue by eugef66** [mulesoft/docs-connectors#1867]
The information regarding "Test Connection" for Workday Connector ( under "Configure a Global Element" #5) is outdated and only applies to version 11 or less.  It doesn't work for version 11 and above

https://docs.mulesoft.com/workday-connector/15.0/workday-connector-studio
https://github.com/mulesoft/docs-connectors/blob/latest/workday/15.0/modules/ROOT/pages/workday-connector-studio.adoc

The correct information is:

- Grant the user account access to Performance_Management service and Get_Degrees operation.( Connector version 11.0 and later )
- For earlier versions, grant the Identity_Management and Get_Workday_Account_Signons ( Older Connector versions  )

Source:  https://help.mulesoft.com/s/article/Workday-Connector-Test-Connectivity-Error-It-Was-Impossible-to-Connect-to-the-Workday-Instance

**Comment by sathya0** [comment]
Hey @eugef66 -- thanks for reporting this. We've updated this information in this PR. https://github.com/mulesoft/docs-connectors/pull/1936
