### ISSUE TITLE
SFTP Connector - Pooling Profile 

### ISSUE THREAD

**Issue by andersoal** [mulesoft/docs-connectors#2311]
The parameter `Initialisation Policy` in Studio shows as `INITIALISE_ONE` as *default* and the documentation `INITIALISE_NONE`.

- [SFTP Connector Reference - Mule 4 - Pooling Profile - Initialisation Policy | MuleSoft Documentation (docs.mulesoft.com)](https://docs.mulesoft.com/sftp-connector/1.6/sftp-documentation#PoolingProfile:~:text=pool%20at%20startup.-,INITIALISE_NONE,-Disabled)

![image](https://github.com/mulesoft/docs-connectors/assets/1809812/8d68e4ee-ad3d-4314-912b-0df668430fca)

![image](https://github.com/mulesoft/docs-connectors/assets/1809812/7a17a99f-75fe-4a79-bfa8-bfbab545aad5)

**Comment by kevintroller** [comment]
Hi @AndyDaSilva52  Thank you for your contribution. We have moved the changes to a new pull request.
https://github.com/mulesoft/docs-connectors/pull/2327
