### ISSUE TITLE
W-16216161 MQTT3 configuration error

### ISSUE THREAD

**Issue by BruceThomson** [mulesoft/docs-connectors#2365]
When trying to use the MQTT3 module I get the following error:

Caused by: org.mule.runtime.api.exception.MuleRuntimeException: Could not create an implicit configuration 'config' for the extension 'MQTT3'

This [knowledge article](https://help.mulesoft.com/s/article/Extensions-generated-from-Mule-Java-SDK-facing-Could-not-create-an-implicit-configuration-config-issues-during-deployment) suggest the module should not contain to capitalize letters and should be renamed to Mqtt3

**Comment by valkyrie69** [comment]
@kevintroller Can you open a ticket to check into this issue and confirm with dev?

**Comment by kevintroller** [comment]
Created W-16216161 to track and work on this request with Connectors dev team. Closing this issue now.
