### ISSUE TITLE
Support for all Salesforce API's in Salesforce connector

### ISSUE THREAD

**Issue by kalyanishere** [mulesoft/docs-connectors#2416]
Currently the Salesforce connector v10.18 (https://docs.mulesoft.com/salesforce-connector/10.18/)  does not support all forms of Salesforce API calls. Like accessing Connect API , Integration Procedures etc. Can the connector be upgraded to support all variants of Salesforce API ?

**Comment by sathya0** [comment]
Hi @kalyanishere! Thanks for your feedback. The feedback here is only for doc improvements. For product improvements, please post your idea in the Ideas Portal here with the MuleSoft category: https://ideas.salesforce.com/s/post
