### ISSUE TITLE
EBS Connector (Before You Begin)

### ISSUE THREAD

**Issue by JosephAllen** [mulesoft/docs-connectors#2435]
The **Before You Begin** Section found here: [Before You Begin](https://github.com/mulesoft/docs-connectors/blob/latest/oracle-ebs-122/2.2/modules/ROOT/pages/index.adoc#before-you-begin) seems incomplete.

Version 0.3.9 has a more detailed  [Before You Begin](https://github.com/mulesoft/docs-connectors/blob/latest/oracle-ebs-122/0.3.9/modules/ROOT/pages/index.adoc#before-you-begin) section showing what need to be done in EBS to expose the  FND_WEB_SEC PL/SQL service and the Oracle EBS REST Service Locator .

**Comment by sathya0** [comment]
Thanks for your feedback @JosephAllen. We will work to update this info

**Comment by sathya0** [comment]
@JosephAllen we merged the change for this issue here https://github.com/mulesoft/docs-connectors/pull/2438. The change will be reflected on the docs site in a few hours. Thank you for your feedback!
