### ISSUE TITLE
JCo initialization failed with java.lang.ExceptionInInitializerError: Illegal JCo archive "sapjco3-3.1.8.jar". It is not allowed to rename or repackage the original archive "sapjco3.jar".

### ISSUE THREAD

**Issue by mkmishra89** [mulesoft/docs-connectors#2491]
I am getting this below Exception while trying to use JCO in my application  : JCo initialization failed with java.lang.ExceptionInInitializerError: Illegal JCo archive "sapjco3-3.1.8.jar". It is not allowed to rename or repackage the original archive "sapjco3.jar".

These are the below code which i am suing: 

<dependency>
<groupId>com.sap.conn.jco</groupId>
<artifactId>sapjco3</artifactId>
<version>3.1.8</version>
</dependency>

<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<stripVersion>true</stripVersion>
							<artifactItems>
								<artifactItem>
									<groupId>com.sap.conn.jco</groupId>
									<artifactId>sapjco3</artifactId>
									<version>3.1.8</version>
									<type>jar</type>
									<outputDirectory>${project.build.directory}/repository/com/sap/conn/jco/sapjco3/3.1.8</outputDirectory>
									<destFileName>sapjco3.jar</destFileName>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>

and installed sapjco3 using this command :mvn install:install-file -Dfile="C:\Users\I555870\Documents\jco\sapjco3.jar" -DgroupId="com.sap.conn.jco" -DartifactId="sapjco3" -Dversion="3.1.8" -Dpackaging="jar"

JCoDestinationManager.getDestination(btpDestination)

 but still getting this error : 

JCo initialization failed with java.lang.ExceptionInInitializerError: Illegal JCo archive "sapjco3-3.1.8.jar". It is not allowed to rename or repackage the original archive "sapjco3.jar".

**Comment by sathya0** [comment]
Hi @mkmishra89, have you looked into this article?
https://help.mulesoft.com/s/article/How-to-use-Maven-to-add-SAP-Connector-dependencies

**Comment by sathya0** [comment]
Hi @mkmishra89, let me know if the above article worked for you. If it did, I will close this PR. Thanks!

**Comment by sathya0** [comment]
Hi @mkmishra89, I'll be closing this issue now. Feel free to reopen if needed. Thanks.
