### ISSUE TITLE
Paths for Images in Dokumentation are wrong

### ISSUE THREAD

**Issue by Repulzer** [mulesoft/docs-connectors#2520]
In this Documentation of [SFTP List](https://github.com/mulesoft/docs-connectors/blob/e7a6663e755b374d3ba0514cd640a88494fa45a9/sftp/1.3/modules/ROOT/pages/sftp-list.adoc) the Paths are wrong and wont bring you to the actual linked Images 

- The Path to the Images currently is:
   - "https://github.com/mulesoft/docs-connectors/blob/latest/sftp/1.3/modules/ROOT/pages/sftp-list-operation-1.png"
 
- The Path to the Images should be: 
   - "https://github.com/mulesoft/docs-connectors/blob/latest/sftp/1.3/modules/ROOT/images/sftp-list-operation-1.png"

sooo it goes to "*/pages/*" instead of "*/images/*"

**Comment by Repulzer** [comment]
Would also be cool to update the Images to show whats described.
You explain how to do this and that, then showing a image with not even half of the mentioned steps.... not really a good example.

**Comment by kevintroller** [comment]
Thank you for your valuable feedback. Use the latest version of SFTP Connector 2.1 here https://docs.mulesoft.com/sftp-connector/latest/sftp-list
