### ISSUE TITLE
files are not saved completly

### ISSUE THREAD

**Issue by mpevreuls** [mulesoft/docs-connectors#2672]
Hi We are using the Azure data lake storage connector to save files to the storage. We noticed that files are written (from 20kb up to 3MB but the last lines of the json files are missing. So the files are incorrect json files and cannot be processed further by the datalake.

Any suggestions ideas what caused this.

![image](https://github.com/user-attachments/assets/88900ff2-3ba7-4240-979e-e82db0a887b8)

so we create the Azurepath, do the magic. Then append the records to the file. Then flush it. And the last 4-10 lines of every file ares missing. NO weired signs are in it.

**This is the last part of the file when it is saved**

        "id": 2581831324,
        "time": "2024-01-01T12:14:00+0000",
        "insertTime": "2024-01-01T12:15:35+0000",
        "seqNbr": 11
      }
    ],
    "truncated": false,
    "skipped": false,
    "serial": "11XZU3",
    "name": "ME.06.06894",
    "thirdPartyId": "SNT3.5 11XZU3",
    "type": "seri"
 

**But it should end like this**

        "id": 2581831324,
        "time": "2024-01-01T12:14:00+0000",
        "insertTime": "2024-01-01T12:15:35+0000",
        "seqNbr": 11
      }
    ],
    "truncated": false,
    "skipped": false,
    "serial": "11XZU3",
    "name": "ME.06.06894",
    "thirdPartyId": "SNT3.5 11XZU3",
    "type": "seri"
    }]

**Comment by sathya0** [comment]
Hi @mpevreuls. Sorry to hear you are experiencing this. This repo is only for reporting issues about the documentation of this connector. If there is a product issue, please reach out to Support/Product team. Thank you.
