### ISSUE TITLE
Missing dependencies for ActiveMQ Artemis

### ISSUE THREAD

**Issue by bangert** [mulesoft/docs-connectors#726]
https://github.com/mulesoft/docs-connectors/blob/latest/modules/ROOT/pages/jms/jms-connector.adoc

on the last paragraph the maven dependency to activemq-kahadb-store seems to be a duplicate / copy-and-paste error from the previous paragraph. it would be more sensible if there was a reference to the activemq artemis dependency, like this:

```
<!-- https://mvnrepository.com/artifact/org.apache.activemq/artemis-jms-client-all -->
<dependency>
    <groupId>org.apache.activemq</groupId>
    <artifactId>artemis-jms-client-all</artifactId>
    <version>2.2.0</version>
</dependency>
```
(I am unsure however, if that would be the correct one.)

**Comment by kevintroller** [comment]
Closed as resolved in https://github.com/mulesoft/docs-connectors/pull/789
