### ISSUE TITLE
Amazon SQS Connector 5.6 - Mule 4 - How to send MessageDedeuplicationId

### ISSUE THREAD

**Issue by ed-sparkes** [mulesoft/docs-connectors#889]
Hi, 

It is not very clear from the documentation how i set the messageDeduplicationId in the SQS Connector for Mule 4

Connector Version : 5.6
Mulesoft Version : 4

Any help would be greatly appreciated. 

Thanks, Ed

**Comment by valkyrie69** [comment]
Hi @ed-sparkes We will look into this. Thank you for leaving your feedback.

**Comment by sathya0** [comment]
Hey @ed-sparkes, thanks for the feedback. We have added the changes in [this PR](https://github.com/mulesoft/docs-connectors/pull/1945).
